image: jangrewe/gitlab-ci-android

variables:
  ANDROID_COMPILE_SDK: "29"
  APP_NAME: "BirdsAndroid"

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .m2/
    - .gradle/

stages:
  - build
  - test
  - package

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  - apt-get update -y && apt-get install wget -y


stages:
  - build  
  - test
  - quality_assurance

assembleDebug:
  stage: build
  script:
    - ./gradlew clean assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

unit_tests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - app/build/reports/tests/
      
static_analysis:
  stage: quality_assurance
  script:
    - ./gradlew testDebugUnitTest jacocoTestReport sonarqube -Dsonar.login=$SONAR_TOKEN
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - app/build/reports/

